In July changes were made to configure.ac in Cbc and Clp that were not propogated to FlopCpp. This commit adds these changes:
-AC_COIN_DEBUG_COMPILE
+AC_COIN_DEBUG_COMPILE(FlopCpp)

-            [cbc_default_solver=$with_val],
+            [cbc_default_solver=$withval],

diff --git a/FlopCpp/configure b/FlopCpp/configure
--- a/FlopCpp/configure
+++ b/FlopCpp/configure
@@ -1075,6 +1075,7 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-debug          compile all projects with debug options tests
+  --enable-debug-flopcpp compile this project (FlopCpp) with debug options
   --enable-static[=PKGS]
                           build static libraries [default=no]
   --disable-dependency-tracking  speeds up one-time build
@@ -1107,6 +1108,11 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-flopcpp-verbosity
+                          specify the debug verbosity level for project
+                          FlopCpp
+  --with-flopcpp-checklevel
+                          specify the sanity check level for project FlopCpp
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
@@ -1748,7 +1754,25 @@ else
   coin_debug_compile=false
 fi;
 
- # m4_ifvaln([],
+# Check whether --enable-debug-flopcpp or --disable-debug-flopcpp was given.
+if test "${enable_debug_flopcpp+set}" = set; then
+  enableval="$enable_debug_flopcpp"
+  case "${enableval}" in
+    yes) coin_debug_compile=true
+         enable_shared=no
+         ;;
+    no)  coin_debug_compile=false
+         ;;
+    *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-debug-flopcpp" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-debug-flopcpp" >&2;}
+   { (exit 1); exit 1; }; }
+         ;;
+ esac
+else
+  :
+fi;
+
+ # m4_ifvaln([FlopCpp],
 
 if test $coin_debug_compile = true; then
   echo "$as_me:$LINENO: result: yes" >&5
@@ -1758,7 +1782,40 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
- # m4_ifvaln([],
+
+# Check whether --with-flopcpp-verbosity or --without-flopcpp-verbosity was given.
+if test "${with_flopcpp_verbosity+set}" = set; then
+  withval="$with_flopcpp_verbosity"
+  coin_flopcpp_verbosity=$withval
+else
+  coin_flopcpp_verbosity=0
+fi;
+
+cat >>confdefs.h <<_ACEOF
+#define COIN_FLOPCPP_VERBOSITY $coin_flopcpp_verbosity
+_ACEOF
+
+
+
+# Check whether --with-flopcpp-checklevel or --without-flopcpp-checklevel was given.
+if test "${with_flopcpp_checklevel+set}" = set; then
+  withval="$with_flopcpp_checklevel"
+  coin_flopcpp_checklevel=$withval
+else
+  coin_flopcpp_checklevel=0
+fi;
+
+cat >>confdefs.h <<_ACEOF
+#define COIN_FLOPCPP_CHECKLEVEL $coin_flopcpp_checklevel
+_ACEOF
+
+
+# We use the following variable to have a string with the upper case
+# version of the project name
+COIN_PRJCT=FLOPCPP
+
+
+ # m4_ifvaln([FlopCpp],
 
 
 
@@ -4725,7 +4782,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4728 "configure"' > conftest.$ac_ext
+  echo '#line 4785 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5859,7 +5916,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5862:" \
+echo "$as_me:5919:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6926,11 +6983,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6929: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6986: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6933: \$? = $ac_status" >&5
+   echo "$as_me:6990: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7194,11 +7251,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7197: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7254: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7201: \$? = $ac_status" >&5
+   echo "$as_me:7258: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7298,11 +7355,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7301: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7358: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7305: \$? = $ac_status" >&5
+   echo "$as_me:7362: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9643,7 +9700,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9646 "configure"
+#line 9703 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9743,7 +9800,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9746 "configure"
+#line 9803 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12087,11 +12144,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12090: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12147: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12094: \$? = $ac_status" >&5
+   echo "$as_me:12151: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12191,11 +12248,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12194: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12251: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12198: \$? = $ac_status" >&5
+   echo "$as_me:12255: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13761,11 +13818,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13764: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13821: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13768: \$? = $ac_status" >&5
+   echo "$as_me:13825: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13865,11 +13922,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13868: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13925: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13872: \$? = $ac_status" >&5
+   echo "$as_me:13929: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16072,11 +16129,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16075: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16132: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16079: \$? = $ac_status" >&5
+   echo "$as_me:16136: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16340,11 +16397,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16343: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16400: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16347: \$? = $ac_status" >&5
+   echo "$as_me:16404: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16444,11 +16501,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16447: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16504: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16451: \$? = $ac_status" >&5
+   echo "$as_me:16508: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20463,7 +20520,7 @@ echo $ECHO_N "checking for CBC default solver... $ECHO_C" >&6
 # Check whether --with-cbc-default-solver or --without-cbc-default-solver was given.
 if test "${with_cbc_default_solver+set}" = set; then
   withval="$with_cbc_default_solver"
-  cbc_default_solver=$with_val
+  cbc_default_solver=$withval
 else
   cbc_default_solver=clp
 fi;
